modules:
  tcl:
    hash_length: 2
  # naming_scheme: '{name}/{version}-{compiler.name}-{compiler.version}'
    all:
      suffixes:
        ^python@3.6.5: 'py3'
        ^python@2.7: 'py2'
        ^openblas: 'openblas'
        ^openmpi: 'ompi'
        ^intelmpi: 'impi'
    intel-parallel-studio:
      filter:
        environment_blacklist: ['PS1']
      environment:
        set:
          FI_PROVIDER_PATH: "/opt/intel/compilers_and_libraries_2019.3.199/linux/mpi/intel64/libfabric/lib/prov"
          FI_PROVIDER: sockets
    petsc:
      environment:
        set:
          PETSC_ARCH: ubuntu+intel
    slepc:
      environment:
        set:
          SLEPC_DIR: /home/ubuntu/softwares/petsc-slepc/slepc-3.11.1 
