---
# tasks file for basic
- name: ensure en locale
  become: yes
  locale_gen:
    name: en_US.UTF-8
    state: present
- name: ensure timezone
  become: yes
  timezone:
    name: "{{ timezone }}"
  register: tz
- name: sync the timezone of rsyslog
  become: yes
  when: tz.changed
  service:
    name: rsyslog
    state: restarted
- name: install some apt packs on nodes
  become: yes
  apt:
    name: "{{ aptpacks }}"
    state: present
    update_cache: yes
- name: ensure ntp sevice is started
  become: yes
  service:
    name: ntp
    state: started
    enabled: yes
- name: update ntp config file on ln node
  become: yes
  template:
    src: ../templates/ntp.conf
    dest: /etc/ntp.conf
    owner: root
    backup: yes
  register: lnntp
  when: inventory_hostname in groups['ln']
- name: restart ntp service on lg node
  become: yes
  service:
    name: ntp
    state: restarted
  when: inventory_hostname in groups['ln'] and lnntp.changed
- name: update ntp config file on cn nodes
  become: yes
  template:
    src: ntp-cn.conf
    dest: /etc/ntp.conf
  register: ntpconfig
  when: inventory_hostname in groups['cn']
- name: restart ntp service on cn nodes
  become: yes
  service:
    name: ntp
    state: restarted
  when: inventory_hostname in groups['cn'] and ntpconfig.changed
- name: update ssh config in all nodes
  become: yes
  copy:
    src: sshd_config
    dest: /etc/ssh/sshd_config
    backup: yes
  register: sshdupdate
- name: ensure ssh server is started
  become: yes
  service:
    name: sshd
    state: started
- name: restart ssh
  become: yes
  service:
    name: sshd
    state: restarted
  when: sshdupdate.changed
- name: remove welcome message
  become: yes
  file:
    path: /etc/update-motd.d/
    mode: '0644'
    state: directory
    recurse: yes
- name: postfix config
  become: yes
  template:
    src: main.cf
    dest: /etc/postfix/main.cf
    backup: yes
  register: postconf
- name: ensure postfix running
  service:
    name: postfix
    state: started
    enabled: yes
  become: yes
- name: reload postfix
  service:
    name: postfix
    state: reloaded
  become: yes
  when: postconf.changed
