---
# tasks file for ganglia
- name: install necessary package for ganglia on ln node
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  when: inventory_hostname in groups['ln']
  with_items:
    - ganglia-monitor=3.6.0-7ubuntu2
    - ganglia-webfrontend
    - gmetad
    - ganglia-monitor-python=3.6.0-7ubuntu2
    - lm-sensors
- name: install package for ganglia on cn nodes
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - ganglia-monitor=3.6.0-7ubuntu2
    - ganglia-monitor-python=3.6.0-7ubuntu2
    - lm-sensors
  when: inventory_hostname in groups['cn']
- name: config gmond in cn nodes
  become: yes
  template:
    src: gmond-cn.conf
    dest: /etc/ganglia/gmond.conf
    backup: yes
  when: inventory_hostname in groups['cn']
  register: gmondc
- name: ensure gmond is started
  become: yes
  service:
    name: ganglia-monitor
    state: started
  when: inventory_hostname in groups['cn']
- name: restart gmond in cn nodes
  become: yes
  service:
    name: ganglia-monitor
    state: restarted
  when: inventory_hostname in groups['cn'] and gmondc.changed
- name: config gmond in ln nodes
  become: yes
  template:
     src: gmond.conf
     dest: /etc/ganglia/gmond.conf
     backup: yes
  when: inventory_hostname in groups['ln']
  register: gmondl
- name: ensure gmond started in ln
  become: yes
  service:
    name: ganglia-monitor
    state: started
    enabled: yes
  when: inventory_hostname in groups['ln']
- name: restart gmond in ln node
  become: yes
  service:
    name: ganglia-monitor
    state: restarted
  when: inventory_hostname in groups['ln'] and gmondl.changed
- name: config gmetad in ln nodes
  become: yes
  template:
    src: gmetad.conf
    dest: /etc/ganglia/gmetad.conf
  when: inventory_hostname in groups['ln']
  register: gmetadc
- name: ensure gmetad started in ln
  become: yes
  service:
    name: gmetad
    state: started
    enabled: yes
  when: inventory_hostname in groups['ln']
- name: restart gmetad in ln node
  become: yes
  service:
    name: gmetad
    state: restarted
  when: inventory_hostname in groups['ln'] and gmetadc.changed
- name: config web interface of ganglia
  become: yes
  template:
    src: ganglia.conf
    dest: /etc/apache2/sites-enabled/ganglia.conf
  when: inventory_hostname in groups['ln']
  register: gweb
- name: install passlib for password protection on apache
  become: yes
  apt:
    name: python3-passlib
    state: present
  when: inventory_hostname in groups['ln']
- name: setup apache passwd
  htpasswd:
    path: /etc/apache2/.htpasswd
    name: "{{ ganglia_http_user }}"
    password: "{{ ganglia_http_pass }}"
    owner: root
    group: www-data
    mode: 0640
  become: yes
  when: inventory_hostname in groups['ln']
  register: passwd
- name: ensure apache is started
  become: yes
  service:
    name: apache2
    state: started
    enabled: yes
  when: inventory_hostname in groups['ln']
- name: restart apache2
  become: yes
  service:
    name: apache2
    state: restarted
  when: inventory_hostname in groups['ln'] and (gweb.changed or passwd.changed)
- name: copy the temperature sensor script
  copy:
    src: temg.sh
    dest: "{{ lookup('env', 'HOME') }}/.temg.sh"
  when: inventory_hostname in groups['ln']
- name: add cpu temperature to crontab
  cron:
    job: "/bin/bash {{ lookup('env', 'HOME') }}/.temg.sh"
    name: "temperature monitoring"
  become: yes
- name: copy gpu monitoring script
  copy:
    src: gpu.sh
    dest: "{{ lookup('env', 'HOME') }}/.gpu.sh"
  when: inventory_hostname in groups['ln']
- name: add gpu script to crontab
  become: yes
  when: inventory_hostname in groups['gn']
  cron: 
    minute: "*/2"
    job: "/bin/bash {{ lookup('env', 'HOME') }}/.gpu.sh"
    name: "gpu monitoring"
- name: copy avail monitoring script
  template:
    src: avail-monitor.sh
    dest: "{{ lookup('env', 'HOME') }}/.avail-monitor.sh"
  when: inventory_hostname in groups['ln']
- name: add avail script to crontab on all nodes
  become: yes
  cron:
    minute: "*/3"
    job: "/bin/bash {{ lookup('env', 'HOME') }}/.avail-monitor.sh"
    name: "avail monitoring"
- name: no mail from crontab
  become: yes
  cronvar:
    name: "MAILTO"
    value: '""'
