network:
  version: 2
  renderer: networkd
  ethernets:
    {{ ansible_facts['default_ipv4']['interface'] }}:
      dhcp4: yes
      gateway4: {{ master_ip }}
      mtu: 9000
      match:
        macaddress: {{ ansible_facts['default_ipv4']['macaddress'] }}
